# Conda build file for package accord
# To build: conda build accord

package:
  name: pool
  version: '0.2'

source:
  path: .

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - airgap=repo_mirror.airgap:main
  noarch: python

requirements:
        #build:
        #  - python >=3.6
        #  - setuptools
        #  - urllib3
        #  - ruamel_yaml
        #  - boto3
        #  - cas-mirror

  run:
    - python >=3.6
    - ruamel-yaml
    - jinja2
    - boto3
    - cas-mirror

test:
  source_files:
    - tests/*
  requires:
    - pytest
  commands:
    - pytest

about:
  home: 'https://github.com/oldarmyc/pool'
  license: 'Apache License, Version 2.0'
  license_file: LICENSE
  license_family: APACHE
  summary: 'Library to run conda mirrors and generate airgap tarball'
  description: 'Library to run conda mirrors and generate airgap tarball'
  dev_url: 'https://github.com/oldarmyc/pool'
